services:
  # Web service
  - type: web
    name: fooddelivery
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn fooddelivery.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: fooddelivery-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        sync: false

  # PostgreSQL database
  - type: pserv
    name: fooddelivery-db
    runtime: postgresql
    plan: free
    ipAllowList: []
